### ISSUE TITLE
ntft.exe/.py says that pill is not installed even tho pillow is installed then immediately closes

### ISSUE THREAD

**Issue by mtboss124** [pbsds/Hatenatools#10]
ntft.exe/.py says that pill is not installed even tho pillow is installed then immediately closes
![image](https://github.com/user-attachments/assets/6434d8d2-91fc-4daa-b9ed-6d879da0ec32)

**Comment by pbsds** [comment]
is it installed in the python2 install?

**Comment by mtboss124** [comment]
yes, pillow still seams to not be found even tho pil is installed using pip under python2
sorry for bad english

**Comment by mtboss124** [comment]
is there a specific pill version you are using?

**Comment by pbsds** [comment]
i have not touched this in 10 years

you may have to change 

https://github.com/pbsds/Hatenatools/blob/d5bb128b7634322fb6d97b37d3a12f040b2bd0ba/NTFT.py#L13

into 

```
from PIL import Image
```
