### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghost** [pbsds/Hatenatools#3]
my compile.bat not working

**Comment by pbsds** [comment]
compile.bat isn't needed to run it, only to distribute it as a binary.

Precompiled binaries can be found here, should you only want those: http://pbsds.github.io/compiles/Hatenatools.7z

If you still want to compile it:

Have you installed pyinstaller?
Could you post the output of the script so i can help debug it?

**Comment by ghost** [comment]
pyinstaller is missing.

**Comment by pbsds** [comment]
That doesn't really give me much to work of. If you're running in the command line or powershell, it should be possible to copy and paste the whole output into here. Please do

**Comment by hazycora** [comment]
their account has been deleted, this should probably be closed
