### ISSUE TITLE
upscaling frames from .ppm files

### ISSUE THREAD

**Issue by wyntrr-end** [pbsds/Hatenatools#4]
This isn't really an issue, but I modified `PPM.py` to allow for frames to be upscaled 6x from their native resolution of 256x192 to 1536x1152, which is triggered by command line flags. It's a bit slow due to multiple nested `for` loops, processing a little over 1 frame per second, but it allows exporting flipnotes that can be viewed much larger than the original size without excessive blurriness.
Is this worth adding to the project?

native frame:
![test_normal](https://user-images.githubusercontent.com/66278138/97254452-62a29c00-17dc-11eb-88e6-bd4362bc57eb.png)

native frame zoomed to fit 1080p screen:
![image](https://user-images.githubusercontent.com/66278138/97254439-5c142480-17dc-11eb-835a-2df0a6b34385.png)

upscaled frame:
![test_big](https://user-images.githubusercontent.com/66278138/97254539-9a114880-17dc-11eb-9d2e-5959f8b183a0.png)

**Comment by pbsds** [comment]
Using `for` loops to write each pixel is inefficient. If we limit ourselves to integer scaling, then we could use numpy vector operations like so:

```python
class PPM:
	...
	def GetFrame(self, frame, scale=1): # frame is the index in self.Frames. Only works if ReadFrames was True when reading the PPM file
		global FramePalette
		if not self.Loaded[1]: return None
		assert isinstance(scale, int) and scale >= 1
		
		Inverted, Colors, Frame = self.Frames[frame]
		
		#Defines the palette:
		Palette = FramePalette[:]
		if Inverted:
			Palette[0], Palette[1] = Palette[1], Palette[0]
		Color1 = Palette[Colors[0]]
		Color2 = Palette[Colors[1]]
		
		out = np.zeros((256 * scale, 192 * scale), dtype=">u4")
		out[:] = Palette[0]
		for dx in range(scale):
			for dy in range(scale):
				out[Frame[1] * scale + dx] = Color2
				out[Frame[0] * scale + dy] = Color1
				
		return out
```

If you could test that this code actually works and make a Pull Request along with your command line argument code, then I'd love to merge it :smiley:

**Comment by wyntrr-end** [comment]
I'm not really knowledgeable about numpy, so I knew that there was likely a more efficient way of doing this, but I hadn't thought about doing this. I will give it a try!

**Comment by wyntrr-end** [comment]
Alright, I added your code instead of mine, and honestly I'm not really sure what it's doing because I don't fully understand the data types with how frames are represented. However, it seems to run a lot more slowly than what I wrote, and it just draws a white screen rather than the actual frame.
With `scale = 2` my code runs on a 105-frame flipnote in 15s, and the above code with the same scaling factor finishes the same flipnote in 57s.

Here's the ridiculous 4 nested `for` loops I wrote to do the upscaling (which I did in WriteImage rather than GetFrame):
```
def WriteImage(image, outputPath, big=False):
	if not hasPIL:
		print "Error: PIL not found!"
		return False
	#if not image: return False

	#	if big: upscale the image 6x (~>1080p) so each original pixel is
	#	represented by a 36-pixel square in the larger version
	if big:
		newImg = np.zeros((len(image)*6, len(image[0])*6), dtype=">u4")

		print ""
		for col in range(len(image)):
			for px in range(len(image[0])):
				for dx in range(6):
					for dy in range(6):
						newImg[col*6+dx][px*6+dy] = image[col][px]
	else:
		newImg = image

	out = newImg.tostring("F")	
	out = Image.frombytes("RGBA", (len(newImg), len(newImg[0])), out)
	
	filetype = outputPath[outputPath.rfind(".")+1:]
	out.save(outputPath, filetype)
	
	return True
```
I just used a hardcoded scaling factor of 6, but it makes a lot of sense to make that scaling factor part of the command line arguments, so I'll probably add that.

**Comment by wyntrr-end** [comment]
@pbsds After a bit of research, it turns out that `np.repeat` was what I needed. >700% speedup compared with my nested `for` loops.
