### ISSUE TITLE
flipnote export as mkv doesn't always create correct length video

### ISSUE THREAD

**Issue by wyntrr-end** [pbsds/Hatenatools#6]
In my testing (PPM.py), I found that because of the way ffmpeg is used with the `-shortest` flag when combining the BGM, if the BGM is shorter than the flipnote, then the video is cut off when the BGM ends, rather than when the flipnote ends. If the BGM is longer or the same length, then this works fine.

Simply removing the `-shortest` flag creates the opposite problem, where it works fine if the BGM is shorter or the same length as the flipnote, but if the BGM track is longer than the flipnote, then the video doesn't get appropriately trimmed and the end becomes somewhat glitched.

I think the ffmpeg encode duration for this step needs to be locked to the duration of the flipnote, rather than dependent on the length of the BGM.

**Comment by pbsds** [comment]
perhaps padding the bgm with zeros could be a solution

**Comment by wyntrr-end** [comment]
> 
> 
> perhaps padding the bgm with zeros could be a solution

not sure how that would work, as i'm not super familiar with dealing with audio.

it seems however that ffmpeg allows for specifying how long the output file should be, so if we pass it the `-t` argument followed by the duration of the flipnote in seconds (not sure if this is already calculated in the script, but is pretty simple to calculate using the number of frames and the calculated framerate), that should work

**Comment by pbsds** [comment]
Try [this](https://github.com/pbsds/Hatenatools/commit/12bf2a1f4650003b5a2db3a759e87de47b857683) change.

**Comment by wyntrr-end** [comment]
@pbsds Sorry it took so long to respond. That change seems to work, but perhaps something like [this ](https://github.com/wyntrr-end/Hatenatools/commit/5f3ee86a676ed859839e6dc9a7f5909c0cbcfb22)might be more elegant? ffmpeg has an option to specify how long the output file should be, and you've already got the necessary information to calculate the appropriate duration.

**Comment by pbsds** [comment]
[Thanks!](https://github.com/pbsds/Hatenatools/commit/ede7c401b498c3ab8e771fce69b614375ddb64e4)
